[phases.setup]
nixPkgs = ['python313', 'gcc']

[phases.install]
cmds = ['python3.13 -m pip install --upgrade pip', 'python3.13 -m pip install -r requirements.txt']

[phases.build]
cmds = ['mkdir -p uploads models exports json_backup logs']

[start]
cmd = 'python3.13 -m uvicorn main:app --host 0.0.0.0 --port $PORT'